apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  interval: 1h
  chart: 
    spec: 
      chart: sealed-secrets
      version: ">=1.15.0-0"
      sourceRef:
        name: sealed-secret
        kind: HelmRepository
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: monitoring
      namespace: monitoring
  values:
    metrics:
      serviceMonitor:
        enabled: true
        namespace: monitoring
        labels:
          release: monitoring
          app: kube-prometheus-stack
      dashboards:
        create: true
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
