apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging
  namespace: logging
spec:
  interval: 5m
  chart: 
    spec: 
      chart: loki-stack
      version: ">=2.8.0"
      sourceRef:
        name: loki
        kind: HelmRepository
        namespace: flux-system
  dependsOn:
    - name: monitoring
      namespace: monitoring  
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    promtail:
      enabled: true
      config:
        clients:
          - url: http://logging-loki:3100/loki/api/v1/push
    fluent-bit:
      enabled: false    
