apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring-namespace.yaml
  - ingress-nginx-namespace.yaml
  - logging-namespace.yaml
  - local-path-provisioner-namespace.yaml
