apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring-namespace.yaml
  - ingress-nginx-namespace.yaml
  - logging-namespace.yaml
  - gitlab-runner-namespace.yaml
  - football-api.yaml
  - local-path-provisioner-namespace.yaml
