---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secret
  namespace: flux-system
spec:
  interval: 15m
  url: https://bitnami-labs.github.io/sealed-secrets
  timeout: 3m
