---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./cluster-api-components.yaml
  #- ./bootstrap.yaml
  #- ./controlplane.yaml
  #- ./infra.yaml
  - ./infrastructure-components
  - ./metallb.yaml
  - https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/releases/download/v0.6.4/bootstrap-components.yaml
  - https://github.com/siderolabs/cluster-api-control-plane-provider-talos/releases/download/v0.5.5/control-plane-components.yaml