---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./cluster-api-components.yaml
  - ./bootstrap.yaml
  - ./controlplane.yaml
  - ./infra.yaml
  - ./metallb.yaml
