---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0
  namespace: flux-system
spec:
  dependsOn:
    - name: sidero
    - name: px-operator
  path: ./kubernetes/infra/clusters/cluster-0/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: proxmox-capi-talos
    namespace: flux-system
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false