---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-csr-approver
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/kubelet-serving
  resources:
  - signers
  verbs:
  - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-csr-approver
subjects:
- kind: ServiceAccount
  name: kubelet-csr-approver
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kubelet-csr-approver

  template:
    metadata:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: kubelet-csr-approver

    spec:
      serviceAccountName: kubelet-csr-approver
      containers:
        - name: kubelet-csr-approver
          image: postfinance/kubelet-csr-approver:v0.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          args:
            - -metrics-bind-address
            - ":8080"
            - -health-probe-bind-address
            - ":8081"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081

          env:
            - name: PROVIDER_REGEX
              value: worker-.|master-.|talos-.
            - name: PROVIDER_IP_PREFIXES
              value: "0.0.0.0/0"
            - name: MAX_EXPIRATION_SECONDS
              value: "86400"
            - name: BYPASS_DNS_RESOLUTION
              value: "true"
            - name: ALLOWED_DNS_NAMES
              value: "1"
            - name: BYPASS_HOSTNAME_CHECK
              value: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal