---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: monitoring
spec:
  path: ./cluster-flux/infra/kube-prometheus-stack/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-repo
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: monitoring
      namespace: monitoring
  interval: 15m
  retryInterval: 1m
  timeout: 3m