---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: px-kaas
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false