---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logging
  namespace: logging
spec:
  path: ./kubernetes/infra/loki/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: proxmox-capi-talos
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: logging
      namespace: logging
  interval: 15m
  retryInterval: 1m
  timeout: 3m