---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sidero
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  path: ./kubernetes/infra/sidero/capi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: proxmox-capi-talos
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false