---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  path: ./cluster-flux/infra/ingress-nginx/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux-repo
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
  interval: 15m
  retryInterval: 1m
  timeout: 3m