---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  path: ./kubernetes/infra/sealed-secrets/sealed-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: proxmox-capi-talos
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sealed-secrets-controller
      namespace: kube-system
  interval: 15m
  retryInterval: 1m
  timeout: 3m