---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sealed-secret-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/bitnami-labs/sealed-secrets.git
  ref:
    tag: v0.19.1
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/helm/sealed-secrets/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secret-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: sealed-secret-source
