---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/infra/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: proxmox-capi-talos
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  interval: 15m
  retryInterval: 1m
  timeout: 3m
