apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: sidero-control-plane-flux-1
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: pve
  node: pve ### If not set it will set automaticly from "pool"
  vmid: 553  ### If not set it will set automaticly
  #pool: prod ### Cluster pool for place VM
  anti-affinity: "" ### The anti-affinity group. VM's with same anti-affinity group will be placed on different nodes
  autostart: true
  autostop: true
  cpu:
    type: host
    sockets: 1
    cores: 2
  memory:
    size: 4096
    balloon: 4096
  network:
    net0:
      model: virtio
      #mac: A2:7B:45:48:9C:E6  ### If not set it will set automaticly
      bridge: vmbr0
      tag: 0 # set to 0 if tag not needed
  disk:
    scsi0:
      storage: local-zfs
      size: 40G
  tags:
    - sidero
    - cluster-flux
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=742b4427-b043-44a3-ab45-004107fc9e23,manufacturer=MTIz,product=MTIz,version=MTIz,serial=MTIz,sku=MTIz,family=MTIz,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=net0;ide2;scsi0"
    ide2: "none,media=cdrom"
    hotplug: "network,disk,usb"
    tablet: 1
    onboot: 0
    kvm: 1
    agent: "0"
    numa: 1
    protection: 0
---
apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: sidero-worker-flux-1
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: pve
  node: pve ### If not set it will set automaticly from "pool"
  vmid: 554  ### If not set it will set automaticly
  #pool: prod ### Cluster pool for place VM
  anti-affinity: "" ### The anti-affinity group. VM's with same anti-affinity group will be placed on different nodes
  autostart: true
  autostop: true
  cpu:
    type: host
    sockets: 1
    cores: 2
  memory:
    size: 4096
    balloon: 4096
  network:
    net0:
      model: virtio
      #mac: A2:7B:45:48:9C:E6  ### If not set it will set automaticly
      bridge: vmbr0
      tag: 0 # set to 0 if tag not needed
  disk:
    scsi0:
      storage: local-zfs
      size: 40G
  tags:
    - sidero
    - cluster-flux
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=76f2639d-ef16-4ee0-ba83-c74092ada703,manufacturer=MTIz,product=MTIz,version=MTIz,serial=MTIz,sku=MTIz,family=MTIz,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=net0;ide2;scsi0"
    ide2: "none,media=cdrom"
    hotplug: "network,disk,usb"
    tablet: 1
    onboot: 0
    kvm: 1
    agent: "0"
    numa: 1
    protection: 0
---
apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: sidero-worker-flux-2
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: pve
  node: pve ### If not set it will set automaticly from "pool"
  vmid: 555  ### If not set it will set automaticly
  #pool: prod ### Cluster pool for place VM
  anti-affinity: "" ### The anti-affinity group. VM's with same anti-affinity group will be placed on different nodes
  autostart: true
  autostop: true
  cpu:
    type: host
    sockets: 1
    cores: 2
  memory:
    size: 4096
    balloon: 4096
  network:
    net0:
      model: virtio
      #mac: A2:7B:45:48:9C:E6  ### If not set it will set automaticly
      bridge: vmbr0
      tag: 0 # set to 0 if tag not needed
  disk:
    scsi0:
      storage: local-zfs
      size: 40G
  tags:
    - sidero
    - cluster-flux
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=fb85947a-ad26-43a2-8a32-6071f3bc4067,manufacturer=MTIz,product=MTIz,version=MTIz,serial=MTIz,sku=MTIz,family=MTIz,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=net0;ide2;scsi0"
    ide2: "none,media=cdrom"
    hotplug: "network,disk,usb"
    tablet: 1
    onboot: 0
    kvm: 1
    agent: "0"
    numa: 1
    protection: 0
---
apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: sidero-worker-flux-3
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: pve
  node: pve ### If not set it will set automaticly from "pool"
  vmid: 556  ### If not set it will set automaticly
  #pool: prod ### Cluster pool for place VM
  anti-affinity: "" ### The anti-affinity group. VM's with same anti-affinity group will be placed on different nodes
  autostart: true
  autostop: true
  cpu:
    type: host
    sockets: 1
    cores: 2
  memory:
    size: 4096
    balloon: 4096
  network:
    net0:
      model: virtio
      #mac: A2:7B:45:48:9C:E6  ### If not set it will set automaticly
      bridge: vmbr0
      tag: 0 # set to 0 if tag not needed
  disk:
    scsi0:
      storage: local-zfs
      size: 40G
  tags:
    - sidero
    - cluster-flux
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=08ebfc6b-53de-42a4-9e5b-7cd060e7836f,manufacturer=MTIz,product=MTIz,version=MTIz,serial=MTIz,sku=MTIz,family=MTIz,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=net0;ide2;scsi0"
    ide2: "none,media=cdrom"
    hotplug: "network,disk,usb"
    tablet: 1
    onboot: 0
    kvm: 1
    agent: "0"
    numa: 1
    protection: 0